# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/lib/python2.7/dist-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /usr/local/lib/python2.7/dist-packages/cmake/data/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/frank/git/brcm_patchram

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/frank/git/brcm_patchram

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/lib/python2.7/dist-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/lib/python2.7/dist-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/lib/python2.7/dist-packages/cmake/data/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/lib/python2.7/dist-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/lib/python2.7/dist-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/lib/python2.7/dist-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/lib/python2.7/dist-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/lib/python2.7/dist-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/frank/git/brcm_patchram/CMakeFiles /home/frank/git/brcm_patchram/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/frank/git/brcm_patchram/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named brcm_patchram_plus_usb

# Build rule for target.
brcm_patchram_plus_usb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 brcm_patchram_plus_usb
.PHONY : brcm_patchram_plus_usb

# fast build rule for target.
brcm_patchram_plus_usb/fast:
	$(MAKE) -f CMakeFiles/brcm_patchram_plus_usb.dir/build.make CMakeFiles/brcm_patchram_plus_usb.dir/build
.PHONY : brcm_patchram_plus_usb/fast

#=============================================================================
# Target rules for targets named brcm_patchram_plus_h5

# Build rule for target.
brcm_patchram_plus_h5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 brcm_patchram_plus_h5
.PHONY : brcm_patchram_plus_h5

# fast build rule for target.
brcm_patchram_plus_h5/fast:
	$(MAKE) -f CMakeFiles/brcm_patchram_plus_h5.dir/build.make CMakeFiles/brcm_patchram_plus_h5.dir/build
.PHONY : brcm_patchram_plus_h5/fast

#=============================================================================
# Target rules for targets named brcm_patchram_plus

# Build rule for target.
brcm_patchram_plus: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 brcm_patchram_plus
.PHONY : brcm_patchram_plus

# fast build rule for target.
brcm_patchram_plus/fast:
	$(MAKE) -f CMakeFiles/brcm_patchram_plus.dir/build.make CMakeFiles/brcm_patchram_plus.dir/build
.PHONY : brcm_patchram_plus/fast

brcm_patchram_plus.o: brcm_patchram_plus.c.o

.PHONY : brcm_patchram_plus.o

# target to build an object file
brcm_patchram_plus.c.o:
	$(MAKE) -f CMakeFiles/brcm_patchram_plus.dir/build.make CMakeFiles/brcm_patchram_plus.dir/brcm_patchram_plus.c.o
.PHONY : brcm_patchram_plus.c.o

brcm_patchram_plus.i: brcm_patchram_plus.c.i

.PHONY : brcm_patchram_plus.i

# target to preprocess a source file
brcm_patchram_plus.c.i:
	$(MAKE) -f CMakeFiles/brcm_patchram_plus.dir/build.make CMakeFiles/brcm_patchram_plus.dir/brcm_patchram_plus.c.i
.PHONY : brcm_patchram_plus.c.i

brcm_patchram_plus.s: brcm_patchram_plus.c.s

.PHONY : brcm_patchram_plus.s

# target to generate assembly for a file
brcm_patchram_plus.c.s:
	$(MAKE) -f CMakeFiles/brcm_patchram_plus.dir/build.make CMakeFiles/brcm_patchram_plus.dir/brcm_patchram_plus.c.s
.PHONY : brcm_patchram_plus.c.s

brcm_patchram_plus_h5.o: brcm_patchram_plus_h5.c.o

.PHONY : brcm_patchram_plus_h5.o

# target to build an object file
brcm_patchram_plus_h5.c.o:
	$(MAKE) -f CMakeFiles/brcm_patchram_plus_h5.dir/build.make CMakeFiles/brcm_patchram_plus_h5.dir/brcm_patchram_plus_h5.c.o
.PHONY : brcm_patchram_plus_h5.c.o

brcm_patchram_plus_h5.i: brcm_patchram_plus_h5.c.i

.PHONY : brcm_patchram_plus_h5.i

# target to preprocess a source file
brcm_patchram_plus_h5.c.i:
	$(MAKE) -f CMakeFiles/brcm_patchram_plus_h5.dir/build.make CMakeFiles/brcm_patchram_plus_h5.dir/brcm_patchram_plus_h5.c.i
.PHONY : brcm_patchram_plus_h5.c.i

brcm_patchram_plus_h5.s: brcm_patchram_plus_h5.c.s

.PHONY : brcm_patchram_plus_h5.s

# target to generate assembly for a file
brcm_patchram_plus_h5.c.s:
	$(MAKE) -f CMakeFiles/brcm_patchram_plus_h5.dir/build.make CMakeFiles/brcm_patchram_plus_h5.dir/brcm_patchram_plus_h5.c.s
.PHONY : brcm_patchram_plus_h5.c.s

brcm_patchram_plus_usb.o: brcm_patchram_plus_usb.c.o

.PHONY : brcm_patchram_plus_usb.o

# target to build an object file
brcm_patchram_plus_usb.c.o:
	$(MAKE) -f CMakeFiles/brcm_patchram_plus_usb.dir/build.make CMakeFiles/brcm_patchram_plus_usb.dir/brcm_patchram_plus_usb.c.o
.PHONY : brcm_patchram_plus_usb.c.o

brcm_patchram_plus_usb.i: brcm_patchram_plus_usb.c.i

.PHONY : brcm_patchram_plus_usb.i

# target to preprocess a source file
brcm_patchram_plus_usb.c.i:
	$(MAKE) -f CMakeFiles/brcm_patchram_plus_usb.dir/build.make CMakeFiles/brcm_patchram_plus_usb.dir/brcm_patchram_plus_usb.c.i
.PHONY : brcm_patchram_plus_usb.c.i

brcm_patchram_plus_usb.s: brcm_patchram_plus_usb.c.s

.PHONY : brcm_patchram_plus_usb.s

# target to generate assembly for a file
brcm_patchram_plus_usb.c.s:
	$(MAKE) -f CMakeFiles/brcm_patchram_plus_usb.dir/build.make CMakeFiles/brcm_patchram_plus_usb.dir/brcm_patchram_plus_usb.c.s
.PHONY : brcm_patchram_plus_usb.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... brcm_patchram_plus_usb"
	@echo "... edit_cache"
	@echo "... brcm_patchram_plus_h5"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... brcm_patchram_plus"
	@echo "... brcm_patchram_plus.o"
	@echo "... brcm_patchram_plus.i"
	@echo "... brcm_patchram_plus.s"
	@echo "... brcm_patchram_plus_h5.o"
	@echo "... brcm_patchram_plus_h5.i"
	@echo "... brcm_patchram_plus_h5.s"
	@echo "... brcm_patchram_plus_usb.o"
	@echo "... brcm_patchram_plus_usb.i"
	@echo "... brcm_patchram_plus_usb.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

